# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор ключевого слова')),
                ('name', models.CharField(max_length=2048, verbose_name='Значение ключевого слова')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор страницы')),
                ('url', models.CharField(max_length=2048, verbose_name='Адрес страницы')),
                ('found_date_time', models.DateTimeField(verbose_name='Дата и время обнаружения страницы системой')),
                ('last_scan_date', models.DateTimeField(verbose_name='Дата и время последней проверки на упоминания')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPageRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Количество упоминаний')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Pages')),
            ],
        ),
        migrations.CreateModel(
            name='Politic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор личности')),
                ('name', models.CharField(max_length=2048, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор сайта')),
                ('name', models.CharField(max_length=2048, verbose_name='Наименование сайта')),
            ],
        ),
        migrations.AddField(
            model_name='personpagerank',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Politic'),
        ),
        migrations.AddField(
            model_name='pages',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Site'),
        ),
        migrations.AddField(
            model_name='keywords',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Politic'),
        ),
    ]
