# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='PersonID',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='SiteID',
        ),
        migrations.RemoveField(
            model_name='personpagerank',
            name='PageID',
        ),
        migrations.RemoveField(
            model_name='personpagerank',
            name='PersonID',
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
        migrations.DeleteModel(
            name='Personpagerank',
        ),
        migrations.DeleteModel(
            name='Persons',
        ),
        migrations.DeleteModel(
            name='Sites',
        ),
    ]
