# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор ключевого слова')),
                ('name', models.CharField(max_length=2048, verbose_name='Значение ключевого слова')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Politic')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор страницы')),
                ('url', models.CharField(max_length=2048, verbose_name='Адрес страницы')),
                ('found_date_time', models.DateTimeField(verbose_name='Дата и время обнаружения страницы системой')),
                ('last_scan_date', models.DateTimeField(verbose_name='Дата и время последней проверки на упоминания')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPageRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField(verbose_name='Рейтинг личности на странице')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Pages')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Politic')),
            ],
        ),
    ]
