# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_keywords_pages_personpagerank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personpagerank',
            old_name='Rank',
            new_name='rank',
        ),
    ]
