# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_keywords_pages_personpagerank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personpagerank',
            name='Rank',
        ),
        migrations.AddField(
            model_name='personpagerank',
            name='rank',
            field=models.IntegerField(default=1, verbose_name='Количество упоминаний'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='politic',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Имя'),
        ),
    ]
