use spp;
insert into `persons` (Name) values ('Путин');
insert into `persons` (Name) values ('Собчак');
insert into `persons` (Name) values ('Навальный');
insert into `persons` (Name) values ('Шойгу');
insert into `keywords` (Name, PersonID) values ('президент', 1);
insert into `keywords` (Name, PersonID) values ('ВВП', 1);
insert into `keywords` (Name, PersonID) values ('Ксюша', 2);
insert into `keywords` (Name, PersonID) values ('Ксения', 2);
insert into `keywords` (Name, PersonID) values ('Алексей', 3);
insert into `keywords` (Name, PersonID) values ('блогер', 3);
insert into `keywords` (Name, PersonID) values ('министр обороны', 4);
insert into `keywords` (Name, PersonID) values ('Сергей Кужугетович', 4);
insert into `sites` (Name) values ('lenta.ru');
insert into `sites` (Name) values ('rbc.ru');
insert into `sites` (Name) values ('ria.ru');
insert into `sites` (Name) values ('interfax.ru');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index1.html', 1, '2017-01-25', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index2.html', 1, '2017-02-14', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index3.html', 1, '2017-03-13', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index4.html', 1, '2017-04-24', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index5.html', 1, '2017-05-27', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index6.html', 2, '2017-01-25', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index7.html', 2, '2017-02-14', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index8.html', 2, '2017-03-13', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index9.html', 2, '2017-04-24', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index10.html', 2, '2017-05-27', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index11.html', 3, '2017-01-25', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index12.html', 3, '2017-02-14', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index13.html', 3, '2017-03-13', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index14.html', 3, '2017-04-24', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index15.html', 3, '2017-05-27', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index11.html', 4, '2017-01-25', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index12.html', 4, '2017-02-14', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index13.html', 4, '2017-03-13', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index14.html', 4, '2017-04-24', '2017-11-04');
insert into `pages` (Url, SiteID, FoundDateTime, LastScanDate) values ('/index15.html', 4, '2017-05-27', '2017-11-04');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '1', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('2', '2', '2');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '3', '1');
insert into `personpagerank` (PersonID, PageID, Rank) values ('4', '4', '1');
insert into `personpagerank` (PersonID, PageID, Rank) values ('2', '5', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '6', '3');
insert into `personpagerank` (PersonID, PageID, Rank) values ('2', '7', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '8', '3');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '9', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('4', '10', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('4', '11', '3');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '12', '2');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '13', '2');
insert into `personpagerank` (PersonID, PageID, Rank) values ('2', '14', '2');
insert into `personpagerank` (PersonID, PageID, Rank) values ('2', '15', '2');
insert into `personpagerank` (PersonID, PageID, Rank) values ('2', '1', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '2', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '3', '3');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '4', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '5', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '6', '1');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '7', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '8', '2');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '9', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '10', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('4', '11', '3');
insert into `personpagerank` (PersonID, PageID, Rank) values ('4', '12', '2');
insert into `personpagerank` (PersonID, PageID, Rank) values ('4', '13', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('4', '14', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('2', '15', '1');
insert into `personpagerank` (PersonID, PageID, Rank) values ('2', '1', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('2', '2', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('2', '3', '3');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '4', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '5', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('2', '6', '3');
insert into `personpagerank` (PersonID, PageID, Rank) values ('2', '7', '3');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '8', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '9', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '10', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '11', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('4', '12', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('4', '13', '1');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '14', '3');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '15', '3');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '16', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '17', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('3', '18', '4');
insert into `personpagerank` (PersonID, PageID, Rank) values ('4', '19', '5');
insert into `personpagerank` (PersonID, PageID, Rank) values ('4', '20', '1');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '17', '3');
insert into `personpagerank` (PersonID, PageID, Rank) values ('1', '16', '3');
insert into `users` (Name, Login, Password, Admin) values ('Саша', 'login1', 'password1', '0');
insert into `users` (Name, Login, Password, Admin) values ('Коля', 'login2', 'passwod2', '0');
insert into `users` (Name, Login, Password, Admin) values ('Петя', 'login3', 'passwod3', '1');
insert into `users` (Name, Login, Password, Admin) values ('Маша', 'login4', 'passwod4', '0');
insert into `users` (Name, Login, Password, Admin) values ('Дима', 'login5', 'passwod5', '1');
insert into `users` (Name, Login, Password, Admin) values ('Настя', 'login6', 'passwod6', '0');
insert into `users` (Name, Login, Password, Admin) values ('Илья', 'login7', 'passwod7', '0');
insert into `users` (Name, Login, Password, Admin) values ('Андрей', 'login8', 'passwod8', '1');
insert into `users` (Name, Login, Password, Admin) values ('Сергей', 'login9', 'passwod9', '0');
insert into `users` (Name, Login, Password, Admin) values ('Денис', 'login10', 'passwod10', '0');
